### PR TITLE
Bugs/misc

### PR DESCRIPTION
**Pull request by ayyubibrahimi**
- renamed `summary` to `allegation_desc` for various departments
- fixed regex patterns to remove error message for various departments
- fixed bugs in cprr_lafayette_pd_2009_2014
- additional cleaning of baton_rouge_da_cprr_2021
- renamed `directive` column to `allegation_desc ` for cprr_new_orleans_da; and introduced an initial_disposition column to data_valid
- removed `charge_uid` in favor of `allegation_uid` for cprr_port_allen
- renamed `dept_desc `to `department_desc`
- split rows with multiple allegations in cprr_new_orleans_so
- In datavalid: reframed `action` to be defined as `final_action` and introduced `initial_action` as a column

### CODE REVIEW

**Review by pckhoi — APPROVED** [review]
LGTM

**Comment by ayyubibrahimi** [comment]
@pckhoi FYI: Yesterday Rajiv asked about another commit to WRGL because he is hoping to introduce the `allegation_desc` field into the allegations table.

**Comment by pckhoi** [comment]
Sure, I will do that tomorrow.

**Comment by ayyubibrahimi** [comment]
Awesome. Thanks! Have a great day.

**Comment by pckhoi** [comment]
@ayyubibrahimi @rajivsinclair couldn't finish today because putting pushing logic down to makefile took more time than expected. Will try to finish tomorrow.

**Comment by ayyubibrahimi** [comment]
Awesome. Have a good night

**Comment by rajivsinclair** [comment]
Sounds good. Thanks for updating us!

**Pull request merged**
