### PR TITLE
enhancement/baton_rouge_so

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
@pckhoi - Please review data changes. Changes are reflected in `new-orleans-pd` repos on WRGL, but this PR is for `baton-rouge-so`.

**Comment by pckhoi** [comment]
Very strange, doesn't look like any changes are made to the Baton Rouge tables.

**Comment by ayyubibrahimi** [comment]
Yes. Very confused myself.

**Comment by pckhoi** [comment]
So looks like all the new data come from `match/cprr_baton_rouge_so_2011_2015.csv`. Even if there are no new personnel, there should be new complaints. Try to run each step in the Baton Rouge fuse script in a notebook.

**Comment by ayyubibrahimi** [comment]
@pckhoi - Still no changes reflected on WRGL based on this PR for `cprr_baton_rouge_so`

**Comment by pckhoi** [comment]
Are you able to detect changes on your local?

**Comment by ayyubibrahimi** [comment]
Yes. The filesize of `fuse/com_baton_rouge_so.csv` increases from `21kb` to `85kb` when `cprr_15` (the newly added table) is included in the `com_df` on my local.

**Comment by ayyubibrahimi** [comment]
@rajivsinclair Here is an example of a `process-data` error

**Comment by pckhoi** [comment]
Same error in this branch:
```bash
make: *** No rule to make target 'data/ocr/advocate_post_ohr_pdfs.csv', needed by 'data/ner/advocate_post_officer_history_reports.csv'.  Stop.
```

One sure way to ensure others can run is to empty all directories managed by DVC. And then just run `dvc pull && make`.

**Comment by ayyubibrahimi** [comment]
Apologies. This bug was addressed in PR #342. Please attempt a re-run.

**Pull request merged**
