### PR TITLE
Add an OCR job queue

### PR DESCRIPTION
**Pull request by pckhoi**
This OCR job queue operates by first filling a source bucket (`gs://k8s-ocr-jobqueue-pdfs`) with images extracted from PDF files. It then schedule a job on Kubernetes to process all images and save results to a sink bucket (`gs://k8s-ocr-jobqueue-results`). I have provided scripts to help operate.

This job queue can be installed on any project by following guidance here: [pckhoi/k8s-ocr-jobqueue](https://github.com/pckhoi/k8s-ocr-jobqueue).

Please read [k8s-ocr-jobqueue/README.md](https://github.com/ppact/processing/blob/2cd09cb/k8s-ocr-jobqueue/README.md) for usage.

### CODE REVIEW

**Comment by pckhoi** [comment]
@ayyubibrahimi going forward, if you happen to update or add new OCR scripts. Please use this OCR job queue, always. You will probably need to install `gsutil` and [kubectl](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl).

@rajivsinclair please give Ayyub `roles/container.developer` so that he can deploy OCR job at will. The LLEAD cluster already has an autoscaled node pool (`pool-ipno`) so I didn't have to create another pool just for OCR. The job is running fine right now. I will check back in a few days to see if it scale down properly.

**Comment by rajivsinclair** [comment]
Ayyub, you should already have the necessary permissions because you are an “owner” of the LLEAD project on Google Cloud. Let me know if you have any permissions issues.

> @rajivsinclair please give Ayyub `roles/container.developer` so that he can deploy OCR job at will. The LLEAD cluster already has an autoscaled node pool (`pool-ipno`) so I didn't have to create another pool just for OCR. The job is running fine right now. I will check back in a few days to see if it scale down properly.

**Comment by rajivsinclair** [comment]
@ayyubibrahimi your Google Cloud Console permissions were only granted to ayyubipno@gmail.com but now I’ve also invited your personal gmail ayyub.ibrahimi@gmail.com

**Review by ayyubibrahimi — APPROVED** [review]
Awesome.

**Comment by ayyubibrahimi** [comment]
Awesome. I'll follow up with any questions. Thanks!

**Pull request merged**
