### PR TITLE
Enhancement/ocr minutes

### PR DESCRIPTION
**Pull request by pckhoi**
- Introduces a workflow for OCR tasks which allow OCR cache sharing (see the last section of README).
- Ported over Tarak's OCR task for minutes files from the [extraction](https://github.com/ppact/extraction) repo.

As always, please run `pip install -r requirements.txt` again after merging this branch.

### CODE REVIEW

**Review by ayyubibrahimi — APPROVED** [review]
Awesome!

**Comment by pckhoi** [comment]
It does strike me as odd that that there are data changes. Perhaps some parts of our pipelines are not deterministic enough.

**Comment by ayyubibrahimi** [comment]
I receive the following message when I run `make` after pulling these changes.

`.deba/deps/ocr.d:3: *** multiple target patterns.  Stop.`

**Comment by pckhoi** [comment]
Can you show me the output of this?
```bash
cat .deba/deps/ocr.d
```

**Comment by pckhoi** [comment]
Also show me output of these please:
```bash
pip freeze | grep deba
```
```bash
make --version
```

**Comment by ayyubibrahimi** [comment]
Ran the following commands from `main` after pulling these changes. Looks like the issue is from my previous experimentation with ocr and deba? Please see:

`cat .deba/deps/ocr.d`
```
$(DEBA_DATA_DIR)/ocr: ; @-mkdir -p $@ 2>/dev/null

$(DEBA_DATA_DIR)/ocr/experiment.csv &: $(DEBA_MD5_DIR)/ocr/ocr_post_officer_history.py.md5 $(DEBA_DATA_DIR)/C:/Users/ayyubi/lleads/processing/data/ocr/post/post_officer_history/input/adams_christopher_p.pdf $(DEBA_DATA_DIR)/C:/Users/ayyubi/lleads/processing/data/ocr/post/post_officer_history/input/adams_christopher_p.pdf | $(DEBA_DATA_DIR)/ocr
        $(call deba_execute,ocr/ocr_post_officer_history.py)
```
`pip freeze | grep deba`
`deba==0.1.5`

`make --version`
```
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ayyubibrahimi** [comment]
Can't seem to overwrite my local dvc cache with the remote.

**Comment by pckhoi** [comment]
@ayyubibrahimi please upgrade GNU Make to version 4.3 as described [here](https://askubuntu.com/questions/1386752/where-to-find-gnu-make-4-3-for-ubuntu-20-04)

And please rename your current `ocr` folder into something else e.g. `_ocr`. And just create a new OCR script from scratch according to the workflow.

The DVC local cache is only there to minimize downloads, it shouldn't affect your work in any way. Just run `dvc pull` whenever you check out a new branch should work in most cases.

And your Deba version seems correct. I would say that once you upgrade, there is no need to revert back to an earlier version.

**Comment by ayyubibrahimi** [comment]
GNU Make has been updated to version 4.3, but I'm still receiving the same message when I run `make`

```
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by pckhoi** [comment]
Please clear out the `ocr` folder as I have said and run this:
```bash
make -B .deba/deps/ocr.d
```
and then run `make` again. Show me the full output for both commands.

**Comment by ayyubibrahimi** [comment]
Sorry. I didn't understand that I should clean it out when you said to rename the folder which I did before. I hhave just cleared out the folder and received the following message when running `make -B .deba/deps/ocr.d`

`.deba/deps/ocr.d:3: *** multiple target patterns.  Stop.`

If i go into the `deps` folder within `deba` and remove the following: 

```
make -B .deba/deps/ocr.d$(DEBA_DATA_DIR)/ocr: ; @-mkdir -p $@ 2>/dev/null

$(DEBA_DATA_DIR)/ocr/experiment.csv &: $(DEBA_MD5_DIR)/ocr/ocr_post_officer_history.py.md5 $(DEBA_DATA_DIR)/C:/Users/ayyubi/lleads/processing/data/ocr/post/post_officer_history/input/adams_christopher_p.pdf $(DEBA_DATA_DIR)/C:/Users/ayyubi/lleads/processing/data/ocr/post/post_officer_history/input/adams_christopher_p.pdf | $(DEBA_DATA_DIR)/ocr
	$(call deba_execute,ocr/ocr_post_officer_history.py)

```

Then I can run `make -B .deba/deps/ocr.d` and `make` without an issue

**Comment by pckhoi** [comment]
The `.deba/deps/<stage>.d` file contains detected rules for any given stage. Usually it get updated when either `deba.yaml` has changed or one of the script in `<stage>` folder has changed. I have no idea why it didn't get updated when you first cleared out the `ocr` folder by renaming it into something else.

But in any case, you can always force that file to update with `make -B .deba/deps/<stage>.d` call. I'm glad that fixed the issue.

**Comment by ayyubibrahimi** [comment]
Awesome. Thanks.

**Pull request merged**
