### PR TITLE
enhancement/nopd_settlements

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
@pckhoi - A `process-data` failure that seems weird as well.

**Comment by pckhoi** [comment]
I ran this branch on my local and saw this error:
```bash
make: *** No rule to make target 'data/ocr/advocate_post_ohr_pdfs.csv', needed by 'data/ner/advocate_post_officer_history_reports.csv'.  Stop.
```
In my opinion, if I pull your code and can't run on my local then we already have a problem. Let's not even talk about fixing anything on Github action when our local doesn't even run correctly.

And this seems to be an elementary yet repeating issue. Let's discuss on our next coding session.

**Comment by ayyubibrahimi** [comment]
Apologies. This bug was addressed in PR #342. Please attempt a re-run.

**Comment by ayyubibrahimi** [comment]
This PR now seems to be functioning correctly.

**Pull request merged**
