### PR TITLE
Enhancement/form recognizer

### PR DESCRIPTION
**Pull request by pckhoi**
- Add scripts to help OCR tasks.
- Add instructions to README.md.

### CODE REVIEW

**Comment by pckhoi** [comment]
@ayyubibrahimi Please look at [this section](https://github.com/ppact/processing/blob/e35f30c50faac7925a40923046ac9b12a929c5b9/README.md#extract-tables-from-pdfs-with-form-recognizer) in the README and later do some OCR tasks with it. I need feedback and it will also be good for the know-how to spread among us.

**Comment by ayyubibrahimi** [comment]
Sounds great. FYI - I might not be able to get to it until early next week.

**Comment by pckhoi** [comment]
@ayyubibrahimi if this looks great to you, please approve.

**Review by ayyubibrahimi — APPROVED** [review]
Awesome.

**Pull request merged**
