### PR TITLE
Upgrade deba

### PR DESCRIPTION
**Pull request by pckhoi**
Deba v0.1.0 does not enforce stage order by default.

### CODE REVIEW

**Comment by pckhoi** [comment]
@ayyubibrahimi looks like this raw file is not committed:
```
make: *** No rule to make target '/runner/_work/data/data/raw/tangipahoa_so/tangipahoa_so_cprr_2013.csv', needed by '/runner/_work/data/data/clean/cprr_tangipahoa_so_2015_2021.csv'. 
```

**Review by ayyubibrahimi — APPROVED** [review]
Awesome.

**Comment by pckhoi** [comment]
Please dvc push that file and commit to this branch.

**Comment by ayyubibrahimi** [comment]
I receive the following error when running `dvc add data/raw`

`ERROR: bad DVC file name 'data/raw.dvc' is git-ignored.`

**Comment by pckhoi** [comment]
The new dvc file is at `raw.dvc` so you should run `dvc add raw.dvc` instead.

**Comment by pckhoi** [comment]
Hmm, that command might not work. Let me know.

**Comment by ayyubibrahimi** [comment]
It doesn't work. Error below:

`ERROR: DVC file 'raw.dvc' cannot be an output.`

**Comment by pckhoi** [comment]
Try this: `dvc add --file raw.dvc data/raw`

**Comment by ayyubibrahimi** [comment]
Worked!

**Comment by ayyubibrahimi** [comment]
Ah. I thought that a force-push was the only way to push bug/tangipahoa_so to this branch, because it wasn't yet being tracked. However, it seems that it overrode more than the `raw.dvc` file.

**Comment by pckhoi** [comment]
Luckily, I can just force push from my local. Never force push anything in ordinary circumstances.

When I said to push to this branch, I meant to checkout this branch on your local. Make the changes on top of it. Then push to Github. Let me know if anything need to be clarified.

**Comment by ayyubibrahimi** [comment]
Yes. Makes perfect sense. I began in that manner, but I changed course. Overthinking. Apologies.

Please review the latest commit.

**Comment by pckhoi** [comment]
@ayyubibrahimi the changes probably come from your previous PRs. Do they look right to you?

**Pull request merged**
