### PR TITLE
Bug/ipm_nopd_cprr_allegations

### PR DESCRIPTION
**Pull request by ayyubibrahimi**
@pckhoi 

Do you remember why we decided to name the charges as `allegations` instead of `charges`?

### CODE REVIEW

**Comment by pckhoi** [comment]
Sorry, I don't recall the reason. Let me ask the web guys to make sure.

**Comment by ayyubibrahimi** [comment]
Also curious as to the thought behind the collapse of both `citizen_race` and `citizen_sex` into the one, `citizen` column``

**Comment by pckhoi** [comment]
Regarding allegation vs charges, could you hold on until next week? I would like to confirm how these columns are being used and the web guys will not get back to me about it until then.

The citizen columns were collapsed because I think there were cases where there are multiple citizens per complaint. Will need to look through the script to make sure but that's the only reason I can think of.

**Comment by ayyubibrahimi** [comment]
Sounds good

**Review by pckhoi — APPROVED** [review]
LGTM

**Pull request merged**
