### PR TITLE
bugs/misc

### PR DESCRIPTION
**Pull request by ayyubibrahimi**
- added `canonicalize_names` function to lib/clean.py

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
@pckhoi Is this what you had in mind?

**Review by pckhoi — APPROVED** [review]
Yes. But this look more like an enhancement and this branch/PR could use a better name.

**Comment by pckhoi** [comment]
@ayyubibrahimi can you add some tests too while you're at it?

**Comment by ayyubibrahimi** [comment]
Yes

**Comment by pckhoi** [comment]
@ayyubibrahimi this stays up for almost a month. Any update?

**Comment by ayyubibrahimi** [comment]
No good one. I got distracted by Spacy and deriving insights from the NOPD data, which you can find [here.](https://www.dropbox.com/scl/fi/9x713ekrmplsjhiolcv04/NOPD-Insights.paper?dl=0&rlkey=k7ounb9cf0o3d8up63z2loi0w) I was waiting to share with you once I had a more clear picture.

This branch will be ready for review shortly.

**Comment by ayyubibrahimi** [comment]
@pckhoi I'm closing this branch in response to your comments above re: label and branch name.

**Pull request closed without merging**
