### PR TITLE
Improve build process

### PR DESCRIPTION
**Pull request by pckhoi**
- Replace `download_inputs.py` with `raw_datasets.json`. From now on raw datasets is written here instead.
- Simplify workflow. From now on it is no longer necessary to update `Makefile` whenever there are changes in script. One simply need to run `make` after any change whatsoever. Make will figure out the correct dependencies and build order automatically.
- All raw files now live under `data/raw`. Thus any raw files loaded using `data_file_path` is now prefixed with `raw/`.
- Update documentation.
- Fix Covington PD scripts.
- Fix LA State CSC scripts.

### CODE REVIEW

**Comment by pckhoi** [comment]
@ayyubibrahimi After this PR is merged let's have a pair session sometime this week. I want to introduce you to the changes in this branch which is quite significant.

**Comment by ayyubibrahimi** [comment]
Thanks. How is Thursday morning/Wednesday night?

**Review by ayyubibrahimi — APPROVED** [review]
Looks great.

**Comment by pckhoi** [comment]
Sounds good, see you then.

**Pull request merged**
